### ISSUE TITLE
我本地为啥起了serve 还是timeout

### ISSUE THREAD

**Issue by xxllp** [GaoQ1/rasa_nlu_gq#10]
TimeoutError: no response from the server (with "timeout"=10000 ms), pleas│  File "src/gevent/__greenlet_primitives.pxd",
e check the following:is the server still online? is the network broken? a│line 35, in gevent.__greenlet_primitives._green
re "port" and "port_out" correct? are you encoding a huge amount of data w│let_switch
hereas the timeout is too small for that?

**Comment by IndoorsNumber31** [comment]
你要看看bert-serving是不是启动成功了，WORKER-0?[0m:ready and listening!  服务的启动日志里要有这一行，不然就是启动不成功
