### ISSUE TITLE
结巴分词存在重复载入词库导致性能下降

### ISSUE THREAD

**Issue by pkdog** [GaoQ1/rasa_nlu_gq#11]
https://github.com/GaoQ1/rasa_nlu_gq/blob/master/rasa_nlu_gao/tokenizers/jieba_tokenizer.py#L78

这里结巴分词器的分词方法存在重复载入自定义词典的问题。这样子会导致引入了自定义词典后，nlu的处理效率大幅度下降

**Comment by GaoQ1** [comment]
你可以提个pr.这个是rasa-nlu里面的，并没有做优化
