### ISSUE TITLE
SeqGAN训练小黄鸡语料

### ISSUE THREAD

**Issue by yufeiyi** [GaoQ1/rasa_nlu_gq#15]
楼主拜读了您用SeqGAN训练生成小黄鸡语料的文章，https://www.ctolib.com/GaoQ1-seqgan.html感到很感兴趣。请问可以分享一下代码吗？不会做商业用途，只为了交流学习。O(∩_∩)O谢谢啦。我的邮箱是yurusu@sina.com

**Comment by GaoQ1** [comment]
https://github.com/GaoQ1/seqgan 我public了
