### ISSUE TITLE
请教大佬个问题，意图识别成功了，但是entities识别不成功，应该调整哪里呢？

### ISSUE THREAD

**Issue by dforel** [GaoQ1/rasa_nlu_gq#16]
请教大佬个问题，意图识别成功了，但是entities识别不成功，应该调整哪里呢？

比如，查询系统医药系统 -------》意图是 查询系统。实体是 医药系统，但是能发现意图，得到的实体为空。jieba分词这里已经添加这些系统的名字到自定义词库了。不知道应该再去优化一下哪里。

大佬有什么建议吗？我想做一个系统查询的助手。
================================================
配置：
  language: "zh"

  pipeline:
  - name: "tokenizer_jieba"
  - name: "bert_vectors_featurizer"
    ip: '127.0.0.1'
    port: 5555
    port_out: 5556
    show_server_config: True
    timeout: 10000
  - name: "intent_classifier_tensorflow_embedding_bert"
  - name: "ner_crf"
  - name: "jieba_pseg_extractor"

==================================================

训练数据
==============================================
{
        "text": "查询系统KPTV-ISMX",
        "intent": "search_system",
        "entities": [
          {
            "start": 4,
            "end": 13,
            "value": "KPTV-ISMX",
            "entity": "sysCode"
          }
        ]
},
{
        "text": "查询系统ISMX",
        "intent": "search_system",
        "entities": [
          {
            "start": 4,
            "end": 8,
            "value": "ISMX",
            "entity": "sysCode"
          }
        ]
      },
{
        "text": "查询系统医药系统",
        "intent": "search_system",
        "entities": [
          {
            "start": 4,
            "end": 8,
            "value": "医药系统",
            "entity": "sysName"
          }
        ]
      },
{
        "text": "查询系统即时通讯系统",
        "intent": "search_system",
        "entities": [
          {
            "start": 4,
            "end": 10,
            "value": "即时通讯系统",
            "entity": "sysName"
          }
        ]
      }
==============================================

**Comment by GaoQ1** [comment]
ner_crf这个不行，针对英文挺友好的，中文的话需要改改

**Comment by dforel** [comment]
> ner_crf这个不行，针对英文挺友好的，中文的话需要改改

谢谢大佬，我去看看怎么改改或者有没有什么替换的插件。

**Comment by GaoQ1** [comment]
我的rasa-nlu-gao中的bilstm_crf就可以替换

**Comment by dforel** [comment]
> 我的rasa-nlu-gao中的bilstm_crf就可以替换

我就是用的你的rasa-nlu-gao。。简直太棒了，以我的三脚猫功夫还改不了插件。。。

**Comment by dforel** [comment]
> 我的rasa-nlu-gao中的bilstm_crf就可以替换

大佬，我今天用 ner_bilstm_crf 来识别实体，可以识别一个了，
但是对于多个实体，比如一个是系统名称，另一个是工单号。就识别的难度很大。
经常把工单号识别为系统编码，工单号是：4090116 这种类型的，系统编码是这种类型的KPTV-ISMX。
系统名称是“”医药系统“”这种的。如果想改良 ner_bilstm_crf 的话，应该从哪方面开始改，有什么学习的文章吗？

**Comment by dforel** [comment]
我是用chatito生成的。
========================
%[search_system]('training': '4000')
    ~[greet?] ~[please?] ~[find?] 系统 @[syscode?]
    ~[greet?] ~[please?] ~[find?] 系统 @[sysname?] 
    ~[please?]~[find?] 系统 @[syscode?] 
    ~[please?]~[find?] 系统 @[sysname?] 
    ~[find?] 系统 @[syscode?] 
    ~[find?] 系统 @[sysname?] 

%[open_taskdetail]('training': '2000')
    ~[greet?] ~[please?] ~[open?] 工单 @[taskId?]
    ~[please?]~[open?] 工单 @[taskId?] 
    ~[open?] 工单 @[taskId?]

**Comment by dforel** [comment]
我这种情况。查询意图准确率还是挺高的，想按照意图来查找命名实体，比如训练多个实体识别模型，不知道这样是否可行？

**Comment by GaoQ1** [comment]
可以，但你需要自己写component了。我也写过根据实体来修改意图的组件的。
