### ISSUE TITLE
bert_as_service组件和bert offline的区别是什么

### ISSUE THREAD

**Issue by gcong66** [GaoQ1/rasa_nlu_gq#17]
大神在rasa里集成的bert_as_service组建和bert offline的区别是什么？二者达到的效果不是一样的？还是大神在用了bert的情况下只用CPU就达到了194个并发，是因为用的bert offline吗？如果是用bert_as_service就需要用GPU，而且单纯CPU也达不到194个并发

**Comment by GaoQ1** [comment]
你理解错了，我说的是整个rasa项目，包括nlu和core

**Comment by gcong66** [comment]
那你写的bert_as_service组件和bert offline的区别是什么?

**Comment by GaoQ1** [comment]
没啥区别，只是提供几种方式。bert-as-service也是将bert提供成一个service
