### ISSUE TITLE
list assignment index out of range的问题

### ISSUE THREAD

**Issue by Ivan-Ji** [GaoQ1/rasa_nlu_gq#22]
在训练nlu模型的时候，出现了如下错误
![image](https://user-images.githubusercontent.com/33078245/64150401-bde83100-ce5a-11e9-93b9-eb8e6cc14a2d.png)
![image](https://user-images.githubusercontent.com/33078245/64150530-03a4f980-ce5b-11e9-8985-f3177d2bea74.png)
自己也检查了训练文件的json格式和编码，出现图片上问题的原因至今还不清楚

**Comment by GaoQ1** [comment]
额。。。这个你试下我里面的数据呢？我觉得你需要debugger调试下

**Comment by Ivan-Ji** [comment]
我使用了CRF之后没出问题，担心是自己语料的问题，只是用模板生成的，会出现语法错误。我也不知道具体是哪句话出了问题，debug也没有结果

**Comment by Ivan-Ji** [comment]
分词之后出现的，调整pipeline的组件顺序也没起到作用
