### ISSUE TITLE
PyLTPEntityExtractor组件不能导入

### ISSUE THREAD

**Issue by Ivan-Ji** [GaoQ1/rasa_nlu_gq#23]
最近使用pyltp的实体抽取的时候，引用组件`rasa_nlu_gao.extractors.pyltp_extractor.PyLTPEntityExtractor`报出没有导入这个组件，但用相同方式导入`rasa_nlu_gao.extractors.bilstm_crf_entity_extractor.BilstmCRFEntityExtractor`却可以，不知道这边是缺少了哪个步骤导致的

**Comment by GaoQ1** [comment]
是不是没有这个py

**Comment by Ivan-Ji** [comment]
好的，我试试其他的组件
