### ISSUE TITLE
是不是一定要支持GPU

### ISSUE THREAD

**Issue by xyjsjruiliu** [GaoQ1/rasa_nlu_gq#24]
Collecting tensorflow-gpu==1.14.0 (from rasa-nlu-gao)
  ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14.0 (from rasa-nlu-gao) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0)
ERROR: No matching distribution found for tensorflow-gpu==1.14.0 (from rasa-nlu-gao)

在使用pip3 install rasa-nlu-gao命令之后遇到上面的问题
当前机器MBP13，系统版本：10.15

**Comment by GaoQ1** [comment]
不一定，那我把配置改下吧
