### ISSUE TITLE
AttributeError: 'BertVectorsFeaturizer' object has no attribute '_combine_with_existing_text_features'

### ISSUE THREAD

**Issue by yangjianxin1** [GaoQ1/rasa_nlu_gq#25]
BertVectorsFeaturizer中调用了_combine_with_existing_text_features方法，是作者粗心敲错方法名了吗？应该改为继承自Featurizer的_combine_with_existing_features方法是吧？

**Comment by yangjianxin1** [comment]
@GaoQ1 我用的rasa版本是1.3.9，Featurizer里只有_combine_with_existing_features这一个方法，可能是改名字了吧，谢谢你

**Comment by KevinTao511** [comment]
Fuaturizer 里已经改为_combine_with_existing_text_features这个方法了

**Comment by baixiaochun001** [comment]
改成 _combine_with_existing_dense_features 或者 _combine_with_existing_sparse_features 就可以了
