### ISSUE TITLE
JiebaPsegExtractor与CRFEntityExtractor抽取的实体重复

### ISSUE THREAD

**Issue by yangjianxin1** [GaoQ1/rasa_nlu_gq#26]
测试了一下，假设nlu文件中存在某个样例text，text中存在name=“李白”，当输入text时，JiebaPsegExtractor与CRFEntityExtractor都会抽取出name="李白"这个实体，如果name的slot type为list，这时候会slot name=[“李白”，“李白”]。也就是JiebaPsegExtractor和CRFEntityExtractor抽取的实体重复了，没有去重，应该在JiebaPsegExtractor中进行去重操作。

**Comment by GaoQ1** [comment]
你可以在action里面选择用哪个
