### ISSUE TITLE
jieba_pseg_extractor pipeline: 自定义词典时遇到的问题

### ISSUE THREAD

**Issue by Natiee** [GaoQ1/rasa_nlu_gq#3]
大佬好，我使用的是jieba词性标注的组件，想要使用我自定义的字典，但是不知该如何加入，在posseg方法中使用jieba. load_userdict()并不能成功，希望可以提示一下

**Comment by GaoQ1** [comment]
额...在jieba_pseg_extractor中我并没有加入jieba.load_userdict的方法。这个方法在jieba_tokenizer组件中已经加了。你使用自定义的字典的话，只需要在使用jieba_tokenizer分词的时候加上就行了。类似于：
`language: "zh"

pipeline:
- name: "tokenizer_jieba"
  dictionary_path: "xx/xx/xx"
- name: "intent_featurizer_wordvector"
  vector: "data/vectors.txt"
- name: "intent_classifier_tensorflow_embedding"

- name: "ner_crf"
- name: "jieba_pseg_extractor"`

**Comment by Natiee** [comment]
ok ，我试过这种方法但是没用加载成功，我再找找问题，谢谢~

**Comment by NexusLee** [comment]
@Natiee 成功了吗 我这好像也不行

**Comment by gcong66** [comment]
@NexusLee @Natiee 你们成功了吗？我设置了dictionary_path: "xx/xx/xx"还是没用

**Comment by NexusLee** [comment]
@gcong66 好了 我路径理解错了 我以为要到具体文件

**Comment by GaoQ1** [comment]
这种问题很简单，要学会调试

**Comment by NexusLee** [comment]
之前因为是pip安装的  后面直接调试的
