### ISSUE TITLE
怎么使用自己预训练的词向量？

### ISSUE THREAD

**Issue by Chenny0808** [GaoQ1/rasa_nlu_gq#31]
Gao大佬，你好，使用自己预训练的词向量的话就要先训练然后使用mitie工具转换成词向量xxx.dat，然后在pipline文件里配置是吗？官网不是说快要弃用mitie了，那以后怎么使用自己训练的词向量呢？

**Comment by GaoQ1** [comment]
我这里面的配置都没有用mitie这种了，可以支持自己预训练的词向量的
