### ISSUE TITLE
BertVectorsFeaturizer好像有个bug

### ISSUE THREAD

**Issue by fuhongyuan** [GaoQ1/rasa_nlu_gq#33]
BertVectorsFeaturizer好像有个bug，当intent训练的数据数量恰好等于batch_size*n+1时(n>=1),如batch_size为128而训练数据量为129或者257时，最后一条数据转bert向量有问题。这种情况下使用EmbeddingBertIntentClassifier会报错：all input arrays must have the same shape。

**Comment by GaoQ1** [comment]
能提个pull request吗 : )

**Comment by fuhongyuan** [comment]
done
