### ISSUE TITLE
windwos下能安装吗，似乎很多问题，即使virtualenv还是不行

### ISSUE THREAD

**Issue by loveJasmine** [GaoQ1/rasa_nlu_gq#7]

**Comment by GaoQ1** [comment]
可以安装，应该没啥问题，我们windows和Linux都在用

**Comment by loveJasmine** [comment]
Collecting tensorflow==1.8.0 (from -r alt_requirements\requirements_tensorflow_sklearn.txt (line 5))
  Could not find a version that satisfies the requirement tensorflow==1.8.0 (from -r alt_requirements\requirements_tensorflow_sklearn.txt (line 5)) (from versions: 1.13.1)
No matching distribution found for tensorflow==1.8.0 (from -r alt_requirements\requirements_tensorflow_sklearn.txt (line 5))

之前那个matploit版本不支持，现在是tensorflow找不到

**Comment by loveJasmine** [comment]
sphinx 需要单独安装

**Comment by loveJasmine** [comment]
还是不行，太多错误

**Comment by loveJasmine** [comment]
终于过了，目前使用bare的requirements, 并且tf版本用最新的，也就是不指定版本好， numpy用1.16.2
